### ISSUE TITLE
linstor-client trows an JSON error trying to parse output with incorrect resource name filter

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#15]
Not sure that it is expected behavior, just wanted to report this:

```
# linstor r l -r 123 
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 627, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 592, in run
    rc = self.parse_and_execute(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 307, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/rsc_cmds.py", line 485, in list
    lstmsg = self._linstor.resource_list(filter_by_nodes=args.nodes, filter_by_resources=args.resources)
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 1264, in resource_list
    return self.volume_list(filter_by_nodes=filter_by_nodes, filter_by_resources=filter_by_resources)
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 1291, in volume_list
    path
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 198, in _rest_request
    error_data = json.loads(error_data_raw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by rp-** [comment]
Thanks for the report, will be fixed with the next linstor-server release

**Comment by kvaps** [comment]
Probably fixed already:
```
linstor r l -r 123 
ERROR:
    The specified resource name '123' is invalid.
```
