### ISSUE TITLE
Unexpected message for API_VERSION

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-client#2]
I'm getting the following error from Linstor client (which is also apparently also breaking `linstor-proxmox`):

```
# linstor node list

Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 555, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 521, in run
    sys.exit(self.parse_and_execute(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 255, in parse_and_execute
    self._linstorapi.connect()
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 1110, in connect
    self._linstor_client.connect(self._ctrl_host)
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 550, in connect
    self._read_api_version_blocking()
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 505, in _read_api_version_blocking
    assert hdr.msg_content == apiconsts.API_VERSION, "Unexpected message for API_VERSION"
AssertionError: Unexpected message for API_VERSION
```

Using Debian packages from `deb http://packages.linbit.com/proxmox/ proxmox-5 drbd-9.0`:
```
ii  linstor-client                       0.6.0-1                                  all          Linstor client command line tool
ii  linstor-server                       0.2.3-1                                  all          linstor-server
ii  python-linstor                       0.6.0-1                                  all          Linstor python api library
```

**Comment by rp-** [comment]
you are using the wrong linstor-server package, we split them into linstor-common, linstor-controller and linstor-satellite.

Latest version is 0.6.2.

The linstor-server will be removed from repos soon.
