### ISSUE TITLE
Proxmox 6.1 | Linstor client broken after applying the latest update (1.0.9-1).

### ISSUE THREAD

**Issue by acidrop** [LINBIT/linstor-client#28]
Proxmox 6.1 | Linstor client broken after applying the latest update (1.0.9-1).

```
root@pve1:~# pveversion 
pve-manager/6.1-5/9bf06119 (running kernel: 5.3.10-1-pve)
```

```
> root@pve1:~# dpkg -l | grep linstor
> ii  linstor-client                       1.0.9-1                                         all          Linstor client command line tool
> ii  linstor-common                       1.4.0-1                                         all          DRBD distributed resource management utility
> ii  linstor-proxmox                      4.1.1-1                                         all          DRBD distributed resource management utility
> ii  linstor-satellite                    1.4.0-1                                         all          DRBD distributed resource management utility
> ii  python-linstor                       1.0.9-1                                         all          Linstor python api library
```

```
root@pve1:~# dpkg -l python3
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=========================================================================
ii  python3        3.7.3-1      amd64        interactive high-level object-oriented language (default python3 version)

```

```
root@pve1:~# linstor
Traceback (most recent call last):
  File "/usr/bin/linstor", line 21, in <module>
    import linstor_client_main
  File "/usr/lib/python3/dist-packages/linstor_client_main.py", line 27, in <module>
    import linstor
ModuleNotFoundError: No module named 'linstor'

```

**Comment by rp-** [comment]
what distribution are you using?
and could you run `find / -name linstorapi.py`

**Comment by acidrop** [comment]
```
root@pve1:~# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
root@pve1:~# find / -name linstorapi.py
/usr/lib/python3.5/dist-packages/linstor/linstorapi.py
```

**Comment by rp-** [comment]
are you using our UBUNTU PPA?

**Comment by acidrop** [comment]
No, I'm using Linbit's Proxmox repository as this is a proxmox system.

**Comment by rck** [comment]
```
$ cat x.sh
#!/bin/bash

for p in 5 6; do
        tmpf=$(mktemp)
        wget -O "$tmpf" -q "https://packages.linbit.com//proxmox/dists/proxmox-${p}/drbd-9.0/binary-amd64/python-linstor_1.0.9-1_all.deb"
        echo -n "This is LINSTOR from the Proxmox $p repo and... "
        dpkg -c "$tmpf" 2>/dev/null | grep -q "python3.5" && echo "You are use the wrong repository!" || echo "That is what you want"
        rm "$tmpf"
done

$ bash x.sh
This is LINSTOR from the Proxmox 5 repo and... You are use the wrong repository!
This is LINSTOR from the Proxmox 6 repo and... That is what you want
```
