### ISSUE TITLE
Too slack version constraints in debian/control

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-client#5]
LINSTOR client throws an error on one of my nodes (packages mostly from Debian "testing"), :
```
# linstor
Traceback (most recent call last):
  File "/usr/bin/linstor", line 21, in <module>
    import linstor_client_main
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 30, in <module>
    import linstor
  File "/usr/lib/python2.7/dist-packages/linstor/__init__.py", line 1, in <module>
    from .linstorapi import ObjectIdentifier
  File "/usr/lib/python2.7/dist-packages/linstor/linstorapi.py", line 23, in <module>
    from linstor.proto.MsgHeader_pb2 import MsgHeader
  File "/usr/lib/python2.7/dist-packages/linstor/proto/MsgHeader_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x1dlinstor/proto/MsgHeader.proto\x12\x18\x63om.linbit.linstor.proto\"\xb3\x01\n\tMsgHeader\x12=\n\x08msg_type\x18\x01 \x01(\x0e\x32+.com.linbit.linstor.proto.MsgHeader.MsgType\x12\x13\n\x0b\x61pi_call_id\x18\x02 \x01(\x03\x12\x13\n\x0bmsg_content\x18\x03 \x01(\t\"=\n\x07MsgType\x12\n\n\x06ONEWAY\x10\x00\x12\x0c\n\x08\x41PI_CALL\x10\x01\x12\n\n\x06\x41NSWER\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```
Versions:

```
# dpkg -l | grep linstor
ii  linstor-client                         0.7.0-1                                 all          Linstor client command line tool
ii  linstor-common                         0.7.1-1                                 all          DRBD distributed resource management utility
ii  linstor-satellite                      0.7.1-1                                 all          DRBD distributed resource management utility
ii  python-linstor                         0.7.0-1                                 all          Linstor python api library

# /usr/bin/python -V
Python 2.7.15+

# dpkg -l | grep -E " (python-natsort|python-protobuf|python) "
ii  python                                 2.7.15-3                                amd64        interactive high-level object-oriented language (Python2 version)
ii  python-linstor                         0.7.0-1                                 all          Linstor python api library
ii  python-natsort                         3.5.1-1                                 all          Natural sorting for python
ii  python-natsort-doc                     3.5.1-1                                 all          Natural sorting for python (doc)
ii  python-protobuf                        2.6.1-1                                 amd64        Python bindings for protocol buffers
ii  python3-natsort                        3.5.1-1                                 all          Natural sorting for python (Python3)
```

**Comment by elonen** [comment]
Turns out upgrading to following package versions fixed it:
```
ii  python-natsort                         5.4.1-1                                 all          Natural sorting for Python
ii  python-protobuf                        3.6.1-4                                 amd64        Python bindings for protocol buffers
```
Maybe add a version constraint on `debian/rules`?

**Comment by rck** [comment]
From where did you get these linstor packages from? As you mention the control file, I assume you build them on your own? Did you build them from a relase tarball from linbit.com? From git?

**Comment by elonen** [comment]
Linbit's Proxmox repository, not building myself. Python packages from Debian repos.

**Comment by rck** [comment]
So to get that right, you built a [FrankenDebian](https://wiki.debian.org/DontBreakDebian) and now it breaks...

Python + Protobuf are *very* picky about versions. One can not expect that code generated with a protobuf compiler version X.something works with python-protobuf version Y.something. That is exactly what happened here with your FrankenDebian.

I don't want to introduce a versioned dependency. The code works with many different combinations (not dependent on a specific version, but on matching combinations). We build for all kinds of Debian based distris. People just have to stay in a Debian series.

**Comment by elonen** [comment]
Debian supports >= or even = operators for package versions, that's how these incompatibilities are supposed to be handled. "Frankendebians" are not an uncommon thing. Please reconsider.
