### ISSUE TITLE
linstor cli tool failed after update to 1.23.1

### ISSUE THREAD

**Issue by MirkoNikolai** [LINBIT/linstor-client#56]
After update to linstor-client to 1.23.1 the cli tool linstor is not working on ubuntu-22.04 the following error ocours
 linstor n l
Traceback (most recent call last):
  File "/usr/bin/linstor", line 21, in <module>
    import linstor_client_main
  File "/usr/lib/python3/dist-packages/linstor_client_main.py", line 31, in <module>
    from linstor_client.commands import (
  File "/usr/lib/python3/dist-packages/linstor_client/commands/__init__.py", line 10, in <module>
    from .rsc_cmds import ResourceCommands
  File "/usr/lib/python3/dist-packages/linstor_client/commands/rsc_cmds.py", line 10, in <module>
    from linstor_client.commands.vlm_cmds import VolumeCommands
  File "/usr/lib/python3/dist-packages/linstor_client/commands/vlm_cmds.py", line 17, in <module>
    from linstor_client.commands.utils.skip_disk_utils import print_skip_disk_info, get_skip_disk_state_str
ModuleNotFoundError: No module named 'linstor_client.commands.utils'

**Comment by rp-** [comment]
Thanks for the report, a fix 1.23.2 was just released

**Comment by MirkoNikolai** [comment]
Thanks for fast responding
